export const matches = [
  {
    "competitionId": "alagoano20a1",
    "round": "1ª",
    "date": "18/07/2026",
    "time": "15:00",
    "homeClubId": "jacioba",
    "awayClubId": "independente-atalaia",
    "stadiumId": "elisio-maia",
    "cityId": "pao-de-acucar",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "1ª",
    "date": "18/07/2026",
    "time": "15:00",
    "homeClubId": "csa",
    "awayClubId": "ponte-preta",
    "stadiumId": "ct-gustavo-paiva",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "1ª",
    "date": "18/07/2026",
    "time": "15:00",
    "homeClubId": "guarani-de-paripueira",
    "awayClubId": "canoense",
    "stadiumId": "municipal-de-paripueira",
    "cityId": "paripueira",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "1ª",
    "date": "18/07/2026",
    "time": "15:00",
    "homeClubId": "desportivo-alianca",
    "awayClubId": "murici-sc",
    "stadiumId": "enokao",
    "cityId": "girau-do-ponciano",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "1ª",
    "date": "18/07/2026",
    "time": "15:00",
    "homeClubId": "asa",
    "awayClubId": "inter-arabia",
    "stadiumId": "ct-noel-alves",
    "cityId": "arapiraca",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "1ª",
    "date": "22/07/2026",
    "time": "15:00",
    "homeClubId": "zumbi",
    "awayClubId": "aa-coruripe",
    "stadiumId": "orlandao",
    "cityId": "uniao-dos-palmares",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "2ª",
    "date": "25/07/2026",
    "time": "15:00",
    "homeClubId": "murici-sc",
    "awayClubId": "guarani-de-paripueira",
    "stadiumId": "jose-gomes-da-costa",
    "cityId": "murici",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "2ª",
    "date": "25/07/2026",
    "time": "15:00",
    "homeClubId": "ponte-preta",
    "awayClubId": "asa",
    "stadiumId": "andradao",
    "cityId": "barra-de-sao-miguel",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "2ª",
    "date": "25/07/2026",
    "time": "15:00",
    "homeClubId": "m10-rio-largo",
    "awayClubId": "desportivo-alianca",
    "stadiumId": "universitario-da-ufal",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "2ª",
    "date": "25/07/2026",
    "time": "15:00",
    "homeClubId": "canoense",
    "awayClubId": "jacioba",
    "stadiumId": "fonsecao",
    "cityId": "lagoa-da-canoa",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "2ª",
    "date": "26/07/2026",
    "time": "15:00",
    "homeClubId": "inter-arabia",
    "awayClubId": "crb",
    "stadiumId": "jose-cicero",
    "cityId": "santa-luzia-do-norte",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "2ª",
    "date": "26/07/2026",
    "time": "15:00",
    "homeClubId": "aa-coruripe",
    "awayClubId": "csa",
    "stadiumId": "gerson-amaral",
    "cityId": "coruripe",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "2ª",
    "date": "26/07/2026",
    "time": "15:00",
    "homeClubId": "miguelense",
    "awayClubId": "cse",
    "stadiumId": "ivson-ferreira",
    "cityId": "sao-bras",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "2ª",
    "date": "28/07/2026",
    "time": "15:00",
    "homeClubId": "u-cse",
    "awayClubId": "m10-rio-largo",
    "stadiumId": "juca-sampaio",
    "cityId": "palmeira-dos-indios",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "3ª",
    "date": "31/07/2026",
    "time": "15:00",
    "homeClubId": "zumbi",
    "awayClubId": "ponte-preta",
    "stadiumId": "orlandao",
    "cityId": "uniao-dos-palmares",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "3ª",
    "date": "31/07/2026",
    "time": "15:00",
    "homeClubId": "crb",
    "awayClubId": "murici-sc",
    "stadiumId": "ct-ninho-do-galo",
    "cityId": "barra-de-sao-miguel",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "3ª",
    "date": "01/08/2026",
    "time": "15:00",
    "homeClubId": "cse",
    "awayClubId": "canoense",
    "stadiumId": "juca-sampaio",
    "cityId": "palmeira-dos-indios",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "3ª",
    "date": "01/08/2026",
    "time": "15:00",
    "homeClubId": "jacioba",
    "awayClubId": "aa-coruripe",
    "stadiumId": "elisio-maia",
    "cityId": "pao-de-acucar",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "3ª",
    "date": "01/08/2026",
    "time": "15:00",
    "homeClubId": "asa",
    "awayClubId": "m10-rio-largo",
    "stadiumId": "clube-do-servidor",
    "cityId": "arapiraca",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "3ª",
    "date": "02/08/2026",
    "time": "15:00",
    "homeClubId": "csa",
    "awayClubId": "miguelense",
    "stadiumId": "ct-gustavo-paiva",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "3ª",
    "date": "02/08/2026",
    "time": "15:00",
    "homeClubId": "desportivo-alianca",
    "awayClubId": "independente-atalaia",
    "stadiumId": "enokao",
    "cityId": "girau-do-ponciano",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "3ª",
    "date": "02/08/2026",
    "time": "15:00",
    "homeClubId": "guarani-de-paripueira",
    "awayClubId": "inter-arabia",
    "stadiumId": "municipal-de-paripueira",
    "cityId": "paripueira",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "4ª",
    "date": "05/08/2026",
    "time": "15:00",
    "homeClubId": "independente-atalaia",
    "awayClubId": "zumbi",
    "stadiumId": "luiz-pontes",
    "cityId": "atalaia",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "4ª",
    "date": "08/08/2026",
    "time": "15:00",
    "homeClubId": "inter-arabia",
    "awayClubId": "csa",
    "stadiumId": "jose-cicero",
    "cityId": "santa-luzia-do-norte",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "4ª",
    "date": "08/08/2026",
    "time": "15:00",
    "homeClubId": "m10-rio-largo",
    "awayClubId": "zumbi",
    "stadiumId": "universitario-da-ufal",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "4ª",
    "date": "08/08/2026",
    "time": "15:00",
    "homeClubId": "independente-atalaia",
    "awayClubId": "asa",
    "stadiumId": "luiz-pontes",
    "cityId": "atalaia",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "4ª",
    "date": "08/08/2026",
    "time": "15:00",
    "homeClubId": "murici-sc",
    "awayClubId": "cse",
    "stadiumId": "jose-gomes-da-costa",
    "cityId": "murici",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "4ª",
    "date": "09/08/2026",
    "time": "15:00",
    "homeClubId": "ponte-preta",
    "awayClubId": "crb",
    "stadiumId": "andradao",
    "cityId": "barra-de-sao-miguel",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "4ª",
    "date": "09/08/2026",
    "time": "15:00",
    "homeClubId": "jacioba",
    "awayClubId": "miguelense",
    "stadiumId": "elisio-maia",
    "cityId": "pao-de-acucar",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "4ª",
    "date": "09/08/2026",
    "time": "15:00",
    "homeClubId": "canoense",
    "awayClubId": "desportivo-alianca",
    "stadiumId": "fonsecao",
    "cityId": "lagoa-da-canoa",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "4ª",
    "date": "09/08/2026",
    "time": "15:00",
    "homeClubId": "aa-coruripe",
    "awayClubId": "guarani-de-paripueira",
    "stadiumId": "gerson-amaral",
    "cityId": "coruripe",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "5ª",
    "date": "12/08/2026",
    "time": "15:00",
    "homeClubId": "crb",
    "awayClubId": "miguelense",
    "stadiumId": "ct-ninho-do-galo",
    "cityId": "barra-de-sao-miguel",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "5ª",
    "date": "15/08/2026",
    "time": "15:00",
    "homeClubId": "csa",
    "awayClubId": "murici-sc",
    "stadiumId": "ct-gustavo-paiva",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "5ª",
    "date": "15/08/2026",
    "time": "15:00",
    "homeClubId": "zumbi",
    "awayClubId": "inter-arabia",
    "stadiumId": "orlandao",
    "cityId": "uniao-dos-palmares",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "5ª",
    "date": "15/08/2026",
    "time": "15:00",
    "homeClubId": "asa",
    "awayClubId": "jacioba",
    "stadiumId": "clube-do-servidor",
    "cityId": "arapiraca",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "5ª",
    "date": "15/08/2026",
    "time": "15:00",
    "homeClubId": "miguelense",
    "awayClubId": "m10-rio-largo",
    "stadiumId": "ivson-ferreira",
    "cityId": "sao-bras",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "5ª",
    "date": "15/08/2026",
    "time": "15:00",
    "homeClubId": "cse",
    "awayClubId": "ponte-preta",
    "stadiumId": "juca-sampaio",
    "cityId": "palmeira-dos-indios",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "5ª",
    "date": "16/08/2026",
    "time": "15:00",
    "homeClubId": "crb",
    "awayClubId": "canoense",
    "stadiumId": "ct-ninho-do-galo",
    "cityId": "barra-de-sao-miguel",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "5ª",
    "date": "16/08/2026",
    "time": "15:00",
    "homeClubId": "guarani-de-paripueira",
    "awayClubId": "independente-atalaia",
    "stadiumId": "municipal-de-paripueira",
    "cityId": "paripueira",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "5ª",
    "date": "16/08/2026",
    "time": "15:00",
    "homeClubId": "desportivo-alianca",
    "awayClubId": "aa-coruripe",
    "stadiumId": "enokao",
    "cityId": "girau-do-ponciano",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "6ª",
    "date": "22/08/2026",
    "time": "15:00",
    "homeClubId": "ponte-preta",
    "awayClubId": "guarani-de-paripueira",
    "stadiumId": "andradao",
    "cityId": "barra-de-sao-miguel",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "6ª",
    "date": "22/08/2026",
    "time": "15:00",
    "homeClubId": "canoense",
    "awayClubId": "miguelense",
    "stadiumId": "fonsecao",
    "cityId": "lagoa-da-canoa",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "6ª",
    "date": "22/08/2026",
    "time": "15:00",
    "homeClubId": "aa-coruripe",
    "awayClubId": "asa",
    "stadiumId": "gerson-amaral",
    "cityId": "coruripe",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "6ª",
    "date": "23/08/2026",
    "time": "15:00",
    "homeClubId": "independente-atalaia",
    "awayClubId": "crb",
    "stadiumId": "luiz-pontes",
    "cityId": "atalaia",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "6ª",
    "date": "23/08/2026",
    "time": "15:00",
    "homeClubId": "m10-rio-largo",
    "awayClubId": "csa",
    "stadiumId": "universitario-da-ufal",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "6ª",
    "date": "23/08/2026",
    "time": "15:00",
    "homeClubId": "inter-arabia",
    "awayClubId": "desportivo-alianca",
    "stadiumId": "jose-cicero",
    "cityId": "santa-luzia-do-norte",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "6ª",
    "date": "23/08/2026",
    "time": "15:00",
    "homeClubId": "jacioba",
    "awayClubId": "cse",
    "stadiumId": "elisio-maia",
    "cityId": "pao-de-acucar",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "6ª",
    "date": "23/08/2026",
    "time": "15:00",
    "homeClubId": "murici-sc",
    "awayClubId": "zumbi",
    "stadiumId": "jose-gomes-da-costa",
    "cityId": "murici",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "7ª",
    "date": "29/08/2026",
    "time": "15:00",
    "homeClubId": "guarani-de-paripueira",
    "awayClubId": "m10-rio-largo",
    "stadiumId": "municipal-de-paripueira",
    "cityId": "paripueira",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "7ª",
    "date": "29/08/2026",
    "time": "15:00",
    "homeClubId": "cse",
    "awayClubId": "inter-arabia",
    "stadiumId": "juca-sampaio",
    "cityId": "palmeira-dos-indios",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "7ª",
    "date": "29/08/2026",
    "time": "15:00",
    "homeClubId": "miguelense",
    "awayClubId": "ponte-preta",
    "stadiumId": "ivson-ferreira",
    "cityId": "sao-bras",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "7ª",
    "date": "29/08/2026",
    "time": "15:00",
    "homeClubId": "csa",
    "awayClubId": "independente-atalaia",
    "stadiumId": "ct-gustavo-paiva",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "7ª",
    "date": "29/08/2026",
    "time": "15:00",
    "homeClubId": "crb",
    "awayClubId": "aa-coruripe",
    "stadiumId": "ct-ninho-do-galo",
    "cityId": "barra-de-sao-miguel",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "7ª",
    "date": "29/08/2026",
    "time": "15:00",
    "homeClubId": "desportivo-alianca",
    "awayClubId": "jacioba",
    "stadiumId": "enokao",
    "cityId": "girau-do-ponciano",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "7ª",
    "date": "29/08/2026",
    "time": "15:00",
    "homeClubId": "zumbi",
    "awayClubId": "canoense",
    "stadiumId": "orlandao",
    "cityId": "uniao-dos-palmares",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "7ª",
    "date": "29/08/2026",
    "time": "15:00",
    "homeClubId": "asa",
    "awayClubId": "murici-sc",
    "stadiumId": "clube-do-servidor",
    "cityId": "arapiraca",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "Ida",
    "date": "",
    "time": "",
    "homeClubId": "8o-colocado",
    "awayClubId": "1o-colocado",
    "stadiumId": "",
    "cityId": "",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "Ida",
    "date": "",
    "time": "",
    "homeClubId": "7o-colocado",
    "awayClubId": "2o-colocado",
    "stadiumId": "",
    "cityId": "",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "Ida",
    "date": "",
    "time": "",
    "homeClubId": "6o-colocado",
    "awayClubId": "3o-colocado",
    "stadiumId": "",
    "cityId": "",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "Ida",
    "date": "",
    "time": "",
    "homeClubId": "5o-colocado",
    "awayClubId": "4o-colocado",
    "stadiumId": "",
    "cityId": "",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "Volta",
    "date": "",
    "time": "",
    "homeClubId": "1o-colocado",
    "awayClubId": "8o-colocado",
    "stadiumId": "",
    "cityId": "",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "Volta",
    "date": "",
    "time": "",
    "homeClubId": "2o-colocado",
    "awayClubId": "7o-colocado",
    "stadiumId": "",
    "cityId": "",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "Volta",
    "date": "",
    "time": "",
    "homeClubId": "3o-colocado",
    "awayClubId": "6o-colocado",
    "stadiumId": "",
    "cityId": "",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "Volta",
    "date": "",
    "time": "",
    "homeClubId": "4o-colocado",
    "awayClubId": "5o-colocado",
    "stadiumId": "",
    "cityId": "",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "Ida",
    "date": "",
    "time": "",
    "homeClubId": "1o-gr-b-ou-e",
    "awayClubId": "1o-gr-b-ou-e",
    "stadiumId": "",
    "cityId": "",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "Ida",
    "date": "",
    "time": "",
    "homeClubId": "1o-gr-c-ou-d",
    "awayClubId": "1o-gr-c-ou-d",
    "stadiumId": "",
    "cityId": "",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "Volta",
    "date": "",
    "time": "",
    "homeClubId": "1o-gr-b-ou-e",
    "awayClubId": "1o-gr-b-ou-e",
    "stadiumId": "",
    "cityId": "",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "Volta",
    "date": "",
    "time": "",
    "homeClubId": "1o-gr-c-ou-d",
    "awayClubId": "1o-gr-c-ou-d",
    "stadiumId": "",
    "cityId": "",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "Ida",
    "date": "",
    "time": "",
    "homeClubId": "1o-gr-f-ou-g",
    "awayClubId": "1o-gr-f-ou-g",
    "stadiumId": "",
    "cityId": "",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a1",
    "round": "Volta",
    "date": "",
    "time": "",
    "homeClubId": "1o-gr-f-ou-g",
    "awayClubId": "1o-gr-f-ou-g",
    "stadiumId": "",
    "cityId": "",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "1ª",
    "date": "24/07/2026",
    "time": "15:00",
    "homeClubId": "dimensao-saude",
    "awayClubId": "dzm",
    "stadiumId": "universitario-da-ufal",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "1ª",
    "date": "25/07/2026",
    "time": "15:00",
    "homeClubId": "sao-domingos",
    "awayClubId": "penedense",
    "stadiumId": "cordeirao",
    "cityId": "marechal-deodoro",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "1ª",
    "date": "25/07/2026",
    "time": "15:00",
    "homeClubId": "cruzeiro",
    "awayClubId": "unec",
    "stadiumId": "clube-do-servidor",
    "cityId": "arapiraca",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "1ª",
    "date": "26/07/2026",
    "time": "15:00",
    "homeClubId": "maceio-ec",
    "awayClubId": "chute-inicial",
    "stadiumId": "universitario-da-ufal",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "1ª",
    "date": "26/07/2026",
    "time": "15:00",
    "homeClubId": "sporting-fc",
    "awayClubId": "santa-cruz",
    "stadiumId": "o-medalhao",
    "cityId": "teotonio-vilela",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "2ª",
    "date": "01/08/2026",
    "time": "15:00",
    "homeClubId": "santa-cruz",
    "awayClubId": "cruzeiro",
    "stadiumId": "municipal-de-paripueira",
    "cityId": "paripueira",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "2ª",
    "date": "01/08/2026",
    "time": "15:00",
    "homeClubId": "dzm",
    "awayClubId": "sao-domingos",
    "stadiumId": "flor-do-cambara",
    "cityId": "passo-de-camaragibe",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "2ª",
    "date": "01/08/2026",
    "time": "15:00",
    "homeClubId": "atletico-sao-jose",
    "awayClubId": "sporting-fc",
    "stadiumId": "luiz-da-silva-maia",
    "cityId": "sao-jose-da-tapera",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "2ª",
    "date": "02/08/2026",
    "time": "15:00",
    "homeClubId": "penedense",
    "awayClubId": "dimensao-saude",
    "stadiumId": "alfredo-leahy",
    "cityId": "penedo",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "2ª",
    "date": "02/08/2026",
    "time": "15:00",
    "homeClubId": "chute-inicial",
    "awayClubId": "ff-sport",
    "stadiumId": "goleiro",
    "cityId": "quebrangulo",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "2ª",
    "date": "02/08/2026",
    "time": "15:00",
    "homeClubId": "cap-paulo-jacinto",
    "awayClubId": "maceio-ec",
    "stadiumId": "jose-chaves-vasconcelos",
    "cityId": "paulo-jacinto",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "3ª",
    "date": "04/08/2026",
    "time": "15:00",
    "homeClubId": "sporting-fc",
    "awayClubId": "dzm",
    "stadiumId": "o-medalhao",
    "cityId": "teotonio-vilela",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "3ª",
    "date": "05/08/2026",
    "time": "15:00",
    "homeClubId": "unec",
    "awayClubId": "santa-cruz",
    "stadiumId": "universitario-da-ufal",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "3ª",
    "date": "05/08/2026",
    "time": "17:00",
    "homeClubId": "cruzeiro",
    "awayClubId": "atletico-sao-jose",
    "stadiumId": "clube-do-servidor",
    "cityId": "arapiraca",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "3ª",
    "date": "06/08/2026",
    "time": "15:00",
    "homeClubId": "sao-domingos",
    "awayClubId": "ff-sport",
    "stadiumId": "cordeirao",
    "cityId": "marechal-deodoro",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "3ª",
    "date": "06/08/2026",
    "time": "15:00",
    "homeClubId": "dimensao-saude",
    "awayClubId": "cap-paulo-jacinto",
    "stadiumId": "universitario-da-ufal",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "4ª",
    "date": "07/08/2026",
    "time": "15:00",
    "homeClubId": "maceio-ec",
    "awayClubId": "sporting-fc",
    "stadiumId": "universitario-da-ufal",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "4ª",
    "date": "08/08/2026",
    "time": "15:00",
    "homeClubId": "santa-cruz",
    "awayClubId": "chute-inicial",
    "stadiumId": "municipal-de-paripueira",
    "cityId": "paripueira",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "4ª",
    "date": "08/08/2026",
    "time": "15:00",
    "homeClubId": "atletico-sao-jose",
    "awayClubId": "penedense",
    "stadiumId": "luiz-da-silva-maia",
    "cityId": "sao-jose-da-tapera",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "4ª",
    "date": "09/08/2026",
    "time": "15:00",
    "homeClubId": "cap-paulo-jacinto",
    "awayClubId": "sao-domingos",
    "stadiumId": "jose-chaves-vasconcelos",
    "cityId": "paulo-jacinto",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "4ª",
    "date": "09/08/2026",
    "time": "15:00",
    "homeClubId": "dzm",
    "awayClubId": "unec",
    "stadiumId": "flor-do-cambara",
    "cityId": "passo-de-camaragibe",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "4ª",
    "date": "09/08/2026",
    "time": "15:00",
    "homeClubId": "ff-sport",
    "awayClubId": "cruzeiro",
    "stadiumId": "universitario-da-ufal",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "5ª",
    "date": "12/08/2026",
    "time": "15:00",
    "homeClubId": "chute-inicial",
    "awayClubId": "atletico-sao-jose",
    "stadiumId": "goleiro",
    "cityId": "quebrangulo",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "5ª",
    "date": "12/08/2026",
    "time": "15:00",
    "homeClubId": "penedense",
    "awayClubId": "maceio-ec",
    "stadiumId": "alfredo-leahy",
    "cityId": "penedo",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "5ª",
    "date": "12/08/2026",
    "time": "15:00",
    "homeClubId": "unec",
    "awayClubId": "cap-paulo-jacinto",
    "stadiumId": "universitario-da-ufal",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "5ª",
    "date": "13/08/2026",
    "time": "15:00",
    "homeClubId": "ff-sport",
    "awayClubId": "dzm",
    "stadiumId": "universitario-da-ufal",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "5ª",
    "date": "13/08/2026",
    "time": "17:00",
    "homeClubId": "cruzeiro",
    "awayClubId": "dimensao-saude",
    "stadiumId": "clube-do-servidor",
    "cityId": "arapiraca",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "6ª",
    "date": "15/08/2026",
    "time": "15:00",
    "homeClubId": "maceio-ec",
    "awayClubId": "cruzeiro",
    "stadiumId": "universitario-da-ufal",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "6ª",
    "date": "15/08/2026",
    "time": "15:00",
    "homeClubId": "sporting-fc",
    "awayClubId": "unec",
    "stadiumId": "o-medalhao",
    "cityId": "teotonio-vilela",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "6ª",
    "date": "15/08/2026",
    "time": "15:00",
    "homeClubId": "cap-paulo-jacinto",
    "awayClubId": "santa-cruz",
    "stadiumId": "jose-chaves-vasconcelos",
    "cityId": "paulo-jacinto",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "6ª",
    "date": "16/08/2026",
    "time": "15:00",
    "homeClubId": "penedense",
    "awayClubId": "ff-sport",
    "stadiumId": "alfredo-leahy",
    "cityId": "penedo",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "6ª",
    "date": "16/08/2026",
    "time": "15:00",
    "homeClubId": "dimensao-saude",
    "awayClubId": "chute-inicial",
    "stadiumId": "universitario-da-ufal",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "6ª",
    "date": "16/08/2026",
    "time": "15:00",
    "homeClubId": "sao-domingos",
    "awayClubId": "atletico-sao-jose",
    "stadiumId": "cordeirao",
    "cityId": "marechal-deodoro",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "7ª",
    "date": "21/08/2026",
    "time": "15:00",
    "homeClubId": "unec",
    "awayClubId": "penedense",
    "stadiumId": "universitario-da-ufal",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "7ª",
    "date": "22/08/2026",
    "time": "15:00",
    "homeClubId": "atletico-sao-jose",
    "awayClubId": "cap-paulo-jacinto",
    "stadiumId": "luiz-da-silva-maia",
    "cityId": "sao-jose-da-tapera",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "7ª",
    "date": "22/08/2026",
    "time": "15:00",
    "homeClubId": "dzm",
    "awayClubId": "maceio-ec",
    "stadiumId": "flor-do-cambara",
    "cityId": "passo-de-camaragibe",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "7ª",
    "date": "22/08/2026",
    "time": "15:00",
    "homeClubId": "chute-inicial",
    "awayClubId": "sao-domingos",
    "stadiumId": "goleiro",
    "cityId": "quebrangulo",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "7ª",
    "date": "23/08/2026",
    "time": "15:00",
    "homeClubId": "santa-cruz",
    "awayClubId": "dimensao-saude",
    "stadiumId": "municipal-de-paripueira",
    "cityId": "paripueira",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  },
  {
    "competitionId": "alagoano20a2",
    "round": "7ª",
    "date": "23/08/2026",
    "time": "15:00",
    "homeClubId": "ff-sport",
    "awayClubId": "sporting-fc",
    "stadiumId": "universitario-da-ufal",
    "cityId": "maceio",
    "homeGoals": null,
    "awayGoals": null,
    "tv": null
  }
] as const;
